INSERT INTO ingredient (nombre, unidad) VALUES
('pollo', 'g'),
('salmón', 'g'),
('carne vacuna', 'g'),
('cerdo', 'g'),
('palta', 'g'),
('vinagre de manzana', 'ml'),
('espárragos', 'g'),
('berenjena', 'g'),
('tomates cherry', 'g'),
('panceta', 'g'),
('polvo de hornear', 'g'),
('vinagre balsámico', 'ml'),
('albahaca', 'g'),
('hojas de albahaca', 'g'),
('arroz basmati', 'g'),
('hoja de laurel', 'unidad'),
('hojas de laurel', 'unidad'),
('osobuco', 'g'),
('lomo de res', 'g'),
('caldo de carne', 'ml'),
('bicarbonato de sodio', 'g'),
('pimienta negra', 'g'),
('porotos borlotti', 'g'),
('pasta moñito', 'g'),
('coñac', 'g'),
('pan', 'g'),
('pan rallado', 'g'),
('brócoli', 'g'),
('lentejas marrones', 'ml'),
('arroz integral', 'g'),
('azúcar morena', 'g'),
('manteca', 'g'),
('cacao', 'g'),
('tomates en lata', 'g'),
('porotos blancos', 'g'),
('cardamomo', 'g'),
('zanahorias', 'g'),
('castañas de cajú', 'g'),
('azúcar impalpable', 'g'),
('pimienta cayena', 'g'),
('apio nabo', 'g'),
('apio', 'g'),
('sal de apio', 'g'),
('echalotes', 'g'),
('queso cheddar', 'g'),
('queso', 'g'),
('hongos', 'g'),
('pechuga de pollo', 'g'),
('patas de pollo', 'g'),
('caldo de pollo', 'ml'),
('garbanzo', 'g'),
('chile en polvo', 'g'),
('ají', 'g'),
('chocolate', 'g'),
('tomates picados', 'g'),
('chorizo', 'g'),
('cilantro', 'g'),
('canela', 'g'),
('rama de canela', 'unidad'),
('clavo de olor', 'g'),
('coco rallado', 'g'),
('crema de coco', 'ml'),
('leche de coco', 'ml'),
('aceite de coco', 'ml'),
('leche condensada', 'ml'),
('culantro', 'g'),
('semillas de cilantro', 'g'),
('almidón de maíz', 'g'),
('crema de leche', 'ml'),
('crema fraîche', 'ml'),
('pepino', 'g'),
('comino', 'g'),
('semillas de comino', 'g'),
('curry en polvo', 'g'),
('azúcar negra', 'g'),
('salsa de soja oscura', 'ml'),
('eneldo', 'g'),
('tomates secos', 'g'),
('mostaza inglesa', 'g'),
('aceite de oliva extra virgen', 'ml'),
('hinojo', 'g'),
('semillas de hinojo', 'g'),
('fenogreco', 'g'),
('queso feta', 'g'),
('salsa de pescado', 'ml'),
('almendras fileteadas', 'g'),
('harina', 'g'),
('tortilla de harina', 'g'),
('papas', 'g'),
('yogur griego', 'g'),
('chauchas', 'g'),
('aceitunas verdes', 'g'),
('almendras molidas', 'g'),
('comino molido', 'g'),
('jengibre molido', 'g'),
('gruyère', 'g'),
('harissa', 'g'),
('crema doble', 'ml'),
('miel', 'g'),
('rábano picante', 'g'),
('salsa picante', 'ml'),
('helado', 'g'),
('orégano italiano', 'g'),
('jalapeño', 'unidad'),
('arroz jazmín', 'g'),
('col rizada', 'g'),
('langostinos', 'g'),
('sal kosher', 'g'),
('cordero', 'g'),
('chuletas de cordero', 'g'),
('carne picada de cordero', 'g'),
('láminas de lasaña', 'g'),
('carne picada magra', 'g'),
('puerro', 'g'),
('limón', 'unidad'),
('jugo de limón', 'ml'),
('ralladura de limón', 'g'),
('limones', 'g'),
('lechuga', 'g'),
('lima', 'unidad'),
('macarrones', 'g'),
('caballa', 'g'),
('mejorana', 'g'),
('dátiles medjool', 'g'),
('leche', 'ml'),
('malvaviscos', 'g'),
('menta', 'g'),
('mozzarella', 'g'),
('hongos champignon', 'g'),
('mostaza', 'g'),
('mostaza en polvo', 'g'),
('semillas de mostaza', 'g'),
('nuez moscada', 'g'),
('aceite', 'ml'),
('aceite de oliva', 'ml'),
('sal de cebolla', 'g'),
('cebollas', 'g'),
('naranja', 'unidad'),
('ralladura de naranja', 'g'),
('orégano', 'g'),
('salsa de ostras', 'ml'),
('pimentón', 'g'),
('jamón crudo', 'g'),
('parmesano', 'g'),
('queso parmesano', 'g'),
('perejil', 'g'),
('mantequilla de maní', 'g'),
('aceite de maní', 'ml'),
('maní', 'g'),
('arvejas', 'g'),
('pecorino', 'g'),
('penne rigate', 'g'),
('pimienta', 'g'),
('piñones', 'g'),
('chocolate amargo', 'g'),
('harina 0000', 'g'),
('tomates perita', 'g'),
('almidón de papa', 'g'),
('gambas', 'g'),
('masa de hojaldre', 'g'),
('mermelada de frambuesa', 'g'),
('ají molido', 'g'),
('ají rojo', 'g'),
('cebolla morada', 'g'),
('morrón rojo', 'g'),
('vino tinto', 'ml'),
('porotos refritos', 'g'),
('arroz', 'g'),
('fideos de arroz', 'g'),
('rigatoni', 'g'),
('rúcula', 'g'),
('avena', 'g'),
('azafrán', 'g'),
('salvia', 'g'),
('sake', 'ml'),
('salsa', 'ml'),
('sal', 'g'),
('manteca con sal', 'g'),
('salchichas', 'g'),
('sal de mar', 'g'),
('harina leudante', 'g'),
('leche descremada', 'ml'),
('semillas de sésamo', 'g'),
('crema agria', 'ml'),
('salsa de soja', 'ml'),
('leche de soja', 'ml'),
('fideos spaghetti', 'g'),
('espinaca', 'g'),
('cebollitas de verdeo', 'g'),
('zapallo', 'g'),
('frutillas', 'g'),
('azúcar', 'g'),
('pasas sultanas', 'g'),
('aceite de girasol', 'ml'),
('pasta de tamarindo', 'g'),
('salsa de pescado tailandesa', 'ml'),
('tomillo', 'g'),
('ketchup', 'g'),
('puré de tomate', 'g'),
('tomates', 'g'),
('atún', 'g'),
('cúrcuma', 'g'),
('nabo', 'g'),
('vainilla', 'g'),
('esencia de vainilla', 'ml'),
('ternera', 'g'),
('aceite vegetal', 'ml'),
('caldo de verduras', 'ml'),
('vinagre', 'ml'),
('agua', 'ml'),
('chips de chocolate blanco', 'g'),
('filete de pescado blanco', 'g'),
('vinagre blanco', 'ml'),
('vino blanco', 'ml'),
('leche entera', 'ml'),
('pan integral', 'g'),
('salsa worcestershire', 'ml'),
('yogur', 'g'),
('zucchini', 'g'),
('queso crema', 'g'),
('azúcar glass', 'g'),
('caramelo', 'g'),
('salsa de caramelo', 'ml'),
('tagliatelle', 'g'),
('fettuccine', 'g'),
('mejillones', 'g'),
('fideos vermicelli', 'g'),
('calamar', 'g'),
('caldo de pescado', 'ml'),
('aceitunas negras', 'g'),
('cebolla', 'g'),
('tomate', 'g'),
('pato', 'g'),
('muslos de pato', 'g'),
('caldo de pollo en cubo', 'g'),
('arvejas azucaradas', 'g'),
('pan francés', 'g'),
('almejas', 'g'),
('passata de tomate', 'g'),
('aceite de colza', 'ml'),
('queso stilton', 'g'),
('pierna de cordero', 'g'),
('paleta de cordero', 'g'),
('damasco', 'g'),
('zapallo anco', 'g'),
('cuscús', 'g'),
('carne picada', 'g'),
('carne picada de pavo', 'g'),
('salsa bbq', 'g'),
('choclo', 'g'),
('grasa de pato', 'g'),
('vinagre de vino tinto', 'ml'),
('romero', 'g'),
('porotos blancos manteca', 'g'),
('porotos pinto', 'g'),
('salsa de tomate', 'ml'),
('mascarpone', 'g'),
('ricota', 'g'),
('damascos secos', 'g'),
('alcaparras', 'g'),
('banana', 'g'),
('frambuesas', 'g'),
('arándanos', 'g'),
('nueces', 'g'),
('nueces pecan', 'g'),
('jarabe de arce', 'g'),
('chips de chocolate negro', 'g'),
('chocolate con leche', 'g'),
('chocolate amargo tableta', 'g'),
('zapallo calabaza', 'g'),
('masa quebrada', 'g'),
('gelatina en hoja', 'g'),
('duraznos', 'g'),
('morrón amarillo', 'g'),
('morrón verde', 'g'),
('zapallos redondos', 'g'),
('tomates en lata enteros', 'g'),
('castañas', 'g'),
('hongos silvestres', 'g'),
('aceite de trufa', 'ml'),
('queso paneer', 'g'),
('pan naan', 'g'),
('lentejas', 'g'),
('porotos kidney', 'g'),
('tahini', 'g'),
('tortillas', 'g'),
('fideos udon', 'g'),
('repollo', 'g'),
('hongos shiitake', 'g'),
('mirin', 'g'),
('aceite de sésamo', 'ml'),
('baguette', 'g'),
('grasa vacuna', 'g'),
('nabo sueco', 'g'),
('jamón cocido', 'g'),
('ostras', 'g'),
('cerveza negra', 'ml'),
('manteca de cerdo', 'g'),
('riñón de cordero', 'g'),
('riñón de res', 'g'),
('abadejo', 'g'),
('abadejo ahumado', 'g'),
('coles de bruselas', 'g'),
('pasas de uva', 'g'),
('grosellas', 'g'),
('crema pastelera', 'ml'),
('grosellas rojas', 'g'),
('moras', 'g'),
('avellanas', 'g'),
('manzanas', 'g'),
('mermelada de damasco', 'g'),
('mazapán', 'g'),
('almendras', 'g'),
('morcilla', 'g'),
('porotos en lata', 'g'),
('harina blanca', 'g'),
('levadura', 'g'),
('frutas secas mixtas', 'g'),
('cereza', 'g'),
('treacle oscuro', 'g'),
('avena gruesa', 'g'),
('huevo', 'unidad'),
('huevos', 'unidad'),
('bouquet garni', 'g'),
('manzanas para cocinar', 'g'),
('queso de cabra', 'g'),
('prosciutto', 'g'),
('manteca sin sal', 'g'),
('queso brie', 'g'),
('estragón', 'g'),
('ciboulette', 'g'),
('peras', 'g'),
('chocolate blanco', 'g'),
('anís estrellado', 'g'),
('arvejas congeladas', 'g'),
('carne picada de cerdo', 'g'),
('mostaza dijon', 'g'),
('tabasco', 'g'),
('aceite de canola', 'ml'),
('bacalao', 'g'),
('carne molida', 'g'),
('arroz para paella', 'g'),
('porotos negros', 'g'),
('filete de anchoa', 'g'),
('masa filo', 'g'),
('agua de azahar', 'ml'),
('grand marnier', 'g'),
('jerez', 'g'),
('agua de rosas', 'ml'),
('batata', 'g'),
('panecillos', 'g'),
('carne picada de cerdo molida', 'g'),
('chuletas de cerdo', 'g'),
('papas yukon gold', 'g'),
('cebolla amarilla', 'g'),
('caldo concentrado de carne', 'g'),
('caldo concentrado de pollo', 'g'),
('mayonesa', 'g'),
('sriracha', 'g'),
('ruibarbo', 'g'),
('pan pita', 'g'),
('trigo burgol', 'g'),
('quinoa', 'g'),
('pepinos en vinagre', 'g'),
('lechuga iceberg', 'g'),
('harina de repostería', 'g'),
('agua tibia', 'ml'),
('agua hirviendo', 'ml'),
('azúcar en polvo', 'g'),
('kielbasa', 'g'),
('salchicha polaca', 'g'),
('chucrut', 'g'),
('semillas de alcaravea', 'g'),
('arenque', 'g'),
('mermelada', 'g'),
('arroz para sushi', 'g'),
('higos', 'g'),
('sidra', 'ml'),
('remolacha', 'g'),
('sardinas', 'g'),
('ciabatta', 'g'),
('trigo sarraceno', 'g'),
('ciruelas pasas', 'g'),
('falafel', 'g'),
('corned beef', 'g'),
('nutella', 'g'),
('cheddar maduro', 'g'),
('caldo de res en cubo', 'g'),
('remolacha cocida', 'g'),
('cacao en polvo', 'g'),
('azúcar rubia', 'g'),
('papas baby', 'g'),
('ají picante en polvo', 'g'),
('hojuelas de ají', 'g'),
('panceta ahumada', 'g'),
('miel clara', 'g'),
('yogur natural', 'g'),
('cinco especias chinas', 'g'),
('salsa de ají dulce', 'ml'),
('canela molida', 'g'),
('muslos de pollo', 'g'),
('alas de pollo', 'g'),
('leche de almendras', 'ml'),
('extracto de almendras', 'ml'),
('mondongo', 'g'),
('chivo', 'g'),
('pasta de anchoas', 'g'),
('ras el hanout', 'g'),
('dulce de leche', 'g'),
('harina de garbanzos', 'g'),
('bife de flanco', 'g'),
('pimentón dulce ahumado', 'g'),
('queso manchego', 'g'),
('jamón ibérico', 'g'),
('maíz seco', 'g'),
('porotos blancos secos', 'g'),
('caldo de mariscos', 'ml'),
('merluza', 'g'),
('vinagre de jerez', 'ml'),
('panceta en lardones', 'g'),
('pan duro', 'g'),
('arándanos rojos secos', 'g'),
('repollo de savoya', 'g'),
('pimentón picante ahumado', 'g'),
('jamón serrano', 'g'),
('sémola', 'g'),
('semillas de amapola', 'g'),
('pasta de curry panang', 'g'),
('hojas de lima kafir', 'g'),
('chiles rojos secos', 'g'),
('pasta de camarón', 'g'),
('galangal', 'g'),
('hierba limón', 'g'),
('cilantro molido', 'g'),
('nuez moscada molida', 'g'),
('fideos de arroz planos', 'g'),
('bife de lomo', 'g'),
('hongos ostra', 'g'),
('jugo de lima', 'ml'),
('lomo de cerdo', 'g'),
('salsa de ají', 'ml'),
('chaucha larga', 'g'),
('trucha', 'g'),
('fideos de arroz vermicelli', 'g'),
('gambas congeladas', 'g'),
('pasta de galangal', 'g'),
('hojas de lima', 'g'),
('fideos de huevo', 'g'),
('brotes de bambú', 'g'),
('paleta de cerdo', 'g'),
('espaldilla de cerdo', 'g'),
('azúcar de palma', 'g'),
('poroto de soja', 'g'),
('tofu marinado', 'g'),
('salsa hoisin', 'ml'),
('repollo colorado', 'g'),
('lubina', 'g'),
('hígado de pollo', 'g'),
('pavo', 'g'),
('hummus', 'g'),
('tempeh', 'g'),
('pasta de pimiento rojo', 'g'),
('melaza de granada', 'ml'),
('menta seca', 'g'),
('pimientos peppadew dulces', 'g'),
('pistacho', 'g'),
('pasta de tahini', 'g'),
('dátiles sin hueso', 'g'),
('lokum', 'g'),
('crema de vainilla', 'ml'),
('pasta de vainilla', 'g'),
('pistachos molidos', 'g'),
('papas nuevas', 'g'),
('harina de sémola', 'g'),
('freekeh', 'g'),
('queso emmentaler', 'g'),
('masa filo (phyllo)', 'g'),
('mermelada de ciruela', 'g'),
('pasta de pistacho', 'g'),
('salchicha kabanos', 'g'),
('bayas congeladas mixtas', 'g'),
('mermelada de grosellas negras', 'g'),
('melaza', 'g'),
('harina de pan', 'g'),
('cacao sin azúcar', 'g'),
('copos de coco', 'g'),
('harina de maíz', 'g'),
('carne de pavo molida', 'g'),
('arvejas amarillas partidas', 'g'),
('porotos blancos navales', 'g'),
('manteca vegetal', 'g'),
('ralladura de galleta graham', 'g'),
('crémor tártaro', 'g'),
('papa russet', 'g'),
('cerveza', 'ml'),
('azúcar caramelizada', 'g'),
('cerezas secas', 'g'),
('caldo de camarones', 'ml'),
('pasta penne', 'g'),
('camarones gigantes', 'g'),
('leche de coco sin azúcar', 'ml'),
('leche condensada azucarada', 'ml'),
('jugo de naranja', 'ml'),
('vinagre de arroz sazonado', 'ml'),
('repollo napa', 'g'),
('hojas de cilantro', 'g'),
('tofu sedoso', 'g'),
('caldo de carne sin sal', 'ml'),
('vino shaoxing', 'ml'),
('brotes de soja', 'g'),
('porotos largos chinos', 'g'),
('chiles secos', 'g'),
('caldo de pollo en polvo', 'ml'),
('piña en trozos', 'g'),
('jugo de piña', 'ml'),
('camarones secos', 'g'),
('harina de trigo sarraceno', 'g'),
('arvejas partidas', 'g'),
('aceite de nuez', 'ml'),
('arroz de postre', 'g'),
('cúrcuma molida', 'g'),
('camarones', 'g'),
('repollo blanco', 'g'),
('papas rojas', 'g'),
('codillo de cerdo', 'g'),
('crema para batir', 'ml'),
('harina de almendras', 'g'),
('bife de costilla', 'g'),
('chimichurri', 'g'),
('entraña', 'g'),
('granada', 'unidad'),
('esencia de almendras', 'ml'),
('bayas de enebro', 'g'),
('granos de pimienta', 'g'),
('chucrut blanco', 'g'),
('hojas de repollo', 'g'),
('castañas cocidas', 'g'),
('arándano rojo', 'g'),
('costillas de cerdo', 'g'),
('semillas de amapola enteras', 'g'),
('mostaza en grano', 'g'),
('harina de maíz fina', 'g'),
('jugo de durazno', 'ml'),
('cuarto trasero de res', 'g'),
('tomate perita seco', 'g'),
('hongos de madera', 'g'),
('ron oscuro', 'ml'),
('ron blanco', 'ml'),
('ron', 'ml'),
('muffins ingleses', 'unidad'),
('vinagre de vino blanco', 'ml'),
('salmón ahumado', 'g'),
('chiles ancho', 'g'),
('pimienta de jamaica', 'g'),
('tofu', 'g'),
('pasta gochujang', 'g'),
('brotes de soja frescos', 'g'),
('fideos', 'g'),
('hongos oreja de madera', 'g'),
('vino de arroz', 'ml'),
('salsa de ciruela', 'ml'),
('pasta de porotos con chile', 'g'),
('arvejas nieve', 'g'),
('harina de arroz', 'g'),
('pak choi', 'g'),
('lubina filetes', 'g'),
('pierna de cordero en trozos', 'g'),
('caldo de cordero', 'ml'),
('rabanitos', 'g'),
('pimienta de sichuan', 'g'),
('azúcar de palma claro', 'g'),
('salsa hoisin dulce', 'ml'),
('pancakes de harina de arroz', 'g'),
('maní tostado', 'g'),
('salmón ahumado desmenuzado', 'g'),
('pececitos', 'g'),
('pechugas de pollo (plural)', 'g'),
('muslos de pollo (plural)', 'g'),
('morrón', 'g'),
('morrón verde pimiento', 'g'),
('morrón rojo pimiento', 'g'),
('fideos soba', 'g'),
('repollo chino', 'g'),
('agua con gas', 'ml'),
('brócoli morado', 'g');